steps:
  - name: node:10.15.1
    entrypoint: yarn
    args: ["install", "--check-files"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["clean"]
  - name: node:10.15.1
    entrypoint: yarn
    args: ["build"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./public", "[ENTER GOOGLE STORAGE URL]"]
